### PR TITLE
fix: include str ivalue type conversion

### LINKED ISSUE #1756: 🐛 [Bug] _Expected to find type str for value why_not_sparsity_fast_path.76 but get nothing._ when trying to partially compile TransformerEncoder
##  Bug Description

When trying to partially compile transformer encoder, you are met with the following error:

```
Expected to find type str for value why_not_sparsity_fast_path.76 but get nothing.
```

## To Reproduce

```py

import torch
import torch.nn as nn

import torch_tensorrt

class TransformerModel(nn.Module):
    def __init__(self, input_dim, hidden_dim, num_layers, num_heads):
        super(TransformerModel, self).__init__()

        # define embedding layer
        self.embedding = nn.Embedding(input_dim, hidden_dim)

        # define transformer encoder
        self.transformer_encoder = nn.TransformerEncoder(
            nn.TransformerEncoderLayer(d_model=hidden_dim, nhead=num_heads),
            num_layers=num_layers
        )

        # define output layer
        self.fc = nn.Linear(hidden_dim, input_dim)

    def forward(self, x):
        # apply embedding layer
        x = self.embedding(x)

        # apply transformer encoder
        x = self.transformer_encoder(x)

        # apply output layer
        x = self.fc(x)

        return x


model = TransformerModel(input_dim=100, hidden_dim=128, num_layers=2, num_heads=4)

input_data = torch.randint(low=0, high=100, size=(32,10)) # sequence length of 10, batch size of 32

input_data = input_data.to("cuda").to(torch.int)
model.to("cuda")
output = model(input_data)
model.eval()

inputs = [
    torch_tensorrt.Input(
        min_shape=[32,10],
        opt_shape=[32,10],
        max_shape=[32,10],
        dtype=torch.int,
    )]

enabled_precisions = {torch.float, torch.half}  # Run with fp16


with torch_tensorrt.logging.graphs():
    trt_ts_module = torch_tensorrt.compile(
        model, inputs=inputs, enabled_precisions=enabled_precisions, require_full_compilation=True
    )

result = trt_ts_module(input_data)

with open("../saved_models/trt_ts_module.ts", "wb") as f:
    torch.jit.save(trt_ts_module, f)
```

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - Torch-TensorRT Version (e.g. 1.0.0): main
 - PyTorch Version (e.g. 1.0): 2.0
 - CPU Architecture: x64
 - OS (e.g., Linux): Linux
 - How you installed `PyTorch` (`conda`, `pip`, `libtorch`, source): source
 - Build command you used (if compiling from source): pip install -e py
 - Are you using local sources or building from archives: archives
 - Python version: 3.9
 - CUDA version: 11.8
 - GPU models and configuration: 3080Ti
 - Any other relevant information:

### PR DESCRIPTION
**Pull request by bowang007**
# Description

Fixes #1756 

## Type of change

Please delete options that are not relevant and/or add your own.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

# Checklist:

- [ ] My code follows the style guidelines of this project (You can use the linters)
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas and hacks
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests to verify my fix or my feature
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have added the relevant labels to my PR in so that relevant reviewers are notified

### CODE REVIEW

**Review by gs-olive — COMMENTED** [review]
Looks good to me, and I've verified that this resolves the error being displayed in #1756. I do see another error when running that model, however, also during partitioning:

```python
/usr/local/lib/python3.8/dist-packages/torch/jit/_recursive.py:266: UserWarning: 'batch_first' was found in ScriptModule constants, but was not actually set in __init__. Consider removing it.
  warnings.warn("'{}' was found in ScriptModule constants, "
Traceback (most recent call last):
  File "issue_1756.py", line 56, in <module>
    trt_ts_module = torch_tensorrt.compile(
  File "~/TensorRT/py/torch_tensorrt/_compile.py", line 125, in compile
    return torch_tensorrt.ts.compile(
  File "~/TensorRT/py/torch_tensorrt/ts/_compiler.py", line 136, in compile
    compiled_cpp_mod = _C.compile_graph(module._c, _parse_compile_spec(spec))
RuntimeError: Expected Tensor but got Uninitialized
```

File: core/partitioning/shape_analysis.cpp [hunk 1]
```diff
@@ -208,6 +208,8 @@ void getSegmentsOutputByRunning(
       jit_inputs_ivalues.push_back(ivalues_maps[input].toGenericDict());
     } else if (input->type()->kind() == torch::jit::TypeKind::DeviceObjType) {
       jit_inputs_ivalues.push_back(ivalues_maps[input].toDevice());
+    } else if (input->type() == (torch::jit::StringType::get())) {
```
Comment (gs-olive) [inline core/partitioning/shape_analysis.cpp:211]: Consider switching to `input->type()->isSubtypeOf(torch::jit::StringType::get())`, for consistency with the above operators (lines 188 - 197)

**Comment by bowang007** [comment]
> Looks good to me, just made a style recommendation, and I've verified that this resolves the error being displayed in #1756. I do see another error now when running that model, however, also during partitioning:
> 
> ```python
> /usr/local/lib/python3.8/dist-packages/torch/jit/_recursive.py:266: UserWarning: 'batch_first' was found in ScriptModule constants, but was not actually set in __init__. Consider removing it.
>   warnings.warn("'{}' was found in ScriptModule constants, "
> Traceback (most recent call last):
>   File "issue_1756.py", line 56, in <module>
>     trt_ts_module = torch_tensorrt.compile(
>   File "~/TensorRT/py/torch_tensorrt/_compile.py", line 125, in compile
>     return torch_tensorrt.ts.compile(
>   File "~/TensorRT/py/torch_tensorrt/ts/_compiler.py", line 136, in compile
>     compiled_cpp_mod = _C.compile_graph(module._c, _parse_compile_spec(spec))
> RuntimeError: Expected Tensor but got Uninitialized
> ```

Yes, I also noticed this one, I'm me cc you for that discussion
