### PR TITLE
fix: `aten::split` behavior with negative indexing

### LINKED ISSUE #1410: 🐛 [Bug] Encountered bug when converting `deepset/roberta-base-squad2` Hugging Face Network
##  Bug Description

When converting the deepset/roberta-base-squad2 Hugging Face network (https://huggingface.co/deepset/roberta-base-squad2) from TorchScript to Torch-TRT, the following error is encountered:

```
RuntimeError: [Error thrown at core/conversion/conversion.cpp:428] Expected eval_list->elements().size() == n->outputs().size() to be true but got false
Size of evaluated results: 3 and node outputs size: 2 must match.
```

## To Reproduce

1. Run `torch_tensorrt.compile` with `deepset/roberta-base-squad2` model as input, using `fp32` precision.
2. Choose fixed input size of `[1, 128]` and enable `truncate_long_and_double` with 8 GB workspace.
3. Pass in model keyword args to disable attention and hidden state outputs

## Expected behavior

Model should successfully compile to Torch-TRT. Specifically, the size of evaluated results and node outputs should be matching

## Environment

 - Torch-TensorRT Version: 1.3.0a0+b70c9132
 - PyTorch Version: 1.13.0.dev20220921+cu116
 - CPU Architecture: Intel Xeon CPU
 - OS: Ubuntu 20.04
 - How you installed PyTorch: pip
 - Build command you used: python setup.py develop
 - Are you using local sources or building from archives: local
 - Python version: 3.8.13
 - CUDA version: 11.6

## Additional context

Bug was reproduced on PyTorch 22.08 and 22.09 containers

### PR DESCRIPTION
**Pull request by gs-olive**
# Description
- Identified issue arising in the deepset/roberta-base-squad2 HuggingFace network (https://huggingface.co/deepset/roberta-base-squad2) during conversion
```
RuntimeError: [Error thrown at core/conversion/conversion.cpp:428] Expected eval_list->elements().size() == n->outputs().size() to be true but got false
Size of evaluated results: 3 and node outputs size: 2 must match.
```
- Bug involves the use of a negative index (-1) when applying the `aten::split` operator
- Improved axis handling in `add_split` to account for negative indexing
- Improved error handling in `add_split` to ensure valid axes for C++ indexing
- Added regression test to replicate error

Fixes #1410 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [ x ] My code follows the style guidelines of this project (You can use the linters)
- [ x ] I have performed a self-review of my own code
- [ x ] I have commented my code, particularly in hard-to-understand areas and hacks
- [ x ] I have made corresponding changes to the documentation
- [ x ] I have added tests to verify my fix or my feature
- [ x ] New and existing unit tests pass locally with my changes
- [ x ] I have added the relevant labels to my PR in so that relevant reviewers are notified

### CODE REVIEW

File: core/conversion/converters/impl/select.cpp [hunk 1]
```diff
@@ -274,7 +280,8 @@ auto select_registrations TORCHTRT_UNUSED =
         .pattern(
             {"aten::index.Tensor(Tensor self, Tensor?[] indices) -> (Tensor)",
              [](ConversionCtx* ctx, const torch::jit::Node* n, args& args) -> bool {
-               // refer to https://github.com/pytorch/pytorch/blob/master/torch/onnx/symbolic_opset9.py#L4627
+               // refer to
+               // https://github.com/pytorch/pytorch/blob/974ad8fa6cc63b89234beb5ebff54c2d42711932/torch/onnx/symbolic_opset9.py#L4627
```
Comment (gs-olive) [inline core/conversion/converters/impl/select.cpp:284]: Switched original link to permalink

**Review by narendasan — APPROVED** [review]
LGTM!
