### PR TITLE
Fix for warning as default stream was used in enqueueV3

### LINKED ISSUE #3190: 🐛 [Bug] Warning as default stream was used in enqueueV3()
##  Bug Description

Some time below warning is seen while running the model.

WARNING: [Torch-TensorRT - Debug Build] - Using default stream in enqueueV3() may lead to performance issues due to additional calls to cudaStreamSynchronize() by TensorRT to ensure correct synchronization. Please use non-default stream instead.

## To Reproduce
It was reproduced with resnet model with multiple interference call. Both use_python_runtime=False/True have issue

```
model = models.resnet18(pretrained=True).eval().to("cuda")
input = torch.randn((1, 3, 224, 224)).to("cuda")
compile_spec = {
    "inputs": [
        torchtrt.Input(
            input.shape, dtype=torch.float, format=torch.contiguous_format
        )
    ],
    "device": torchtrt.Device("cuda:0"),
    "enabled_precisions": {torch.float},
    "ir": "dynamo",
    "cache_built_engines": False,
    "reuse_cached_engines": False,
    "use_python_runtime": True,
}

trt_mod = torchtrt.compile(model, **compile_spec)
for i in range(5):
    trt_mod(input)
# Clean up model env
torch._dynamo.reset()
```

## Expected behavior

No warning message

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - Torch-TensorRT Version (e.g. 1.0.0):
 - PyTorch Version (e.g. 1.0):
 - CPU Architecture:
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source):
 - Build command you used (if compiling from source):
 - Are you using local sources or building from archives:
 - Python version:
 - CUDA version:
 - GPU models and configuration:
 - Any other relevant information:

### PR DESCRIPTION
**Pull request by keehyuna**
# Description

torch.cuda.current_stream()/c10::cuda::getCurrentCUDAStream() always returns default stream and it leads running enqueueV3() with default stream.
torch.cuda.set_stream/c10::cuda::setCurrentCUDAStream is required to set current stream when new stream is acquired from pool

Fixes #3190

## Type of change

Please delete options that are not relevant and/or add your own.

- Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] My code follows the style guidelines of this project (You can use the linters)
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas and hacks
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests to verify my fix or my feature
- [x] New and existing unit tests pass locally with my changes
- [x] I have added the relevant labels to my PR in so that relevant reviewers are notified

### CODE REVIEW

**Comment by narendasan** [comment]
@keehyuna there is some code related to cudagraphs, can you check how it handles streams and perhaps write some docs on how the runtime is suppose to do streams in all cases?

**Comment by peri044** [comment]
- Add a doc (runtime) which explains how streams work in our runtime. (2nd part of this task)

File: core/runtime/execute_engine.cpp [hunk 1]
```diff
@@ -333,7 +331,7 @@ std::vector<at::Tensor> execute_engine(std::vector<at::Tensor> inputs, c10::intr
       if (need_cudagraphs_record) {
         // If cudagraphs needs to record a graph, capture the enqueueV3 call in a graph
         c10::cuda::CUDAStream recording_stream = compiled_engine->engine_stream;
-        compiled_engine->cudagraph.capture_begin(compiled_engine->cudagraph_mempool_id);
```
Comment (keehyuna) [inline core/runtime/execute_engine.cpp:336]: This was reverted to fix below assert() from torch. We don't share memory across captures, I think we can use internally created pool.

https://pytorch.org/docs/stable/notes/cuda.html#graph-memory-management

```
  File "/root/trt/TensorRT/py/torch_tensorrt/dynamo/runtime/_TorchTensorRTModule.py", line 274, in forward
    outputs: List[torch.Tensor] = torch.ops.tensorrt.execute_engine(
  File "/root/.pyenv/versions/3.10.14/lib/python3.10/site-packages/torch/_ops.py", line 1113, in __call__
    return self._op(*args, **(kwargs or {}))
RuntimeError: it->second->use_count > 0 INTERNAL ASSERT FAILED at "../c10/cuda/CUDACachingAllocator.cpp":2056, please report a bug to PyTorch
```

File: py/torch_tensorrt/dynamo/runtime/_PythonTorchTensorRTModule.py [hunk 2]
```diff
@@ -464,7 +461,8 @@ def cudagraphs_validate_shapes(self, inputs: Sequence[torch.Tensor]) -> bool:
         if new_shape_key != self.shape_key:
             logger.debug(f"Resetting Cudagraph on new shape key {new_shape_key}")
             self.shape_key = new_shape_key
-            self.cudagraph.reset()  # type: ignore
+            if self.cudagraph:
+                self.cudagraph.reset()
```
Comment (keehyuna) [inline py/torch_tensorrt/dynamo/runtime/_PythonTorchTensorRTModule.py:465]: self.cudagraph can be None when torch_compile backend is used.

self.cudagraph is initialized when cudagraphs mode is enabled. But this init was called at compile()
https://github.com/pytorch/TensorRT/blob/main/py/torch_tensorrt/dynamo/runtime/_PythonTorchTensorRTModule.py#L144-L145

**Review by keehyuna — COMMENTED** [review]
This is when problem happend. capture stream is changed to default and non default stream.
image

This is when torch.cuda.set_stream() is used. Non default stream is used for cuda graph/enqueueV3(). But stream is not restored after Forward()
image.

This is proposed fix to keep side stream to cuda graph or enqueueV3()
image

**Review by narendasan — APPROVED** [review]
Good catch LGTM

**Comment by narendasan** [comment]
@lanluo-nvidia please cherry-pick
