### PR TITLE
fix: CUDA error 710 bugfix

### LINKED ISSUE #1418: 🐛 [Bug] Encountered cuda 710 error when apply Torch-TensorRT to BERT
##  Bug Description

I wanted to use Torch-TensorRT to boost BERT model inference, but met following errors:

../aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [239,0,0], thread: [32,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [239,0,0], thread: [33,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [239,0,0], thread: [34,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [239,0,0], thread: [35,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [239,0,0], thread: [36,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [239,0,0], thread: [37,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [239,0,0], thread: [38,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [239,0,0], thread: [39,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [239,0,0], thread: [40,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [239,0,0], thread: [41,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

**_CUDA initialization failure with error: 710. Please check your CUDA installation:  http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html
Segmentation fault (core dumped)_**

## To Reproduce

```python
from transformers import BertModel, BertTokenizer, BertConfig
import numpy as np
import torch
import torch_tensorrt
import time

print("VERSION:", torch_tensorrt.__version__)

# Creating a dummy input
test_batchsz = 128
tokens_tensor = torch.ones((test_batchsz, 20)).to(torch.int32).cuda()
segments_tensors = torch.zeros((test_batchsz, 20)).to(torch.int32).cuda()
mask_tensors = torch.ones((test_batchsz, 20)).to(torch.int32).cuda()

model = BertModel.from_pretrained("bert-base-chinese", torchscript=True)
torch_script_module = torch.jit.trace(model.eval().cuda(), (tokens_tensor, mask_tensors, segments_tensors))

trt_ts_module = torch_tensorrt.compile(torch_script_module.float(),
                        inputs= [torch_tensorrt.Input(shape=[test_batchsz, 20], dtype=torch.int32),
                        torch_tensorrt.Input(shape=[test_batchsz, 20], dtype=torch.int32),
                        torch_tensorrt.Input(shape=[test_batchsz, 20], dtype=torch.int32),
                        ], 
                        enabled_precisions= {torch.float},
                        workspace_size=2000000000,
                        truncate_long_and_double=True)

```

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - Torch-TensorRT Version (e.g. 1.0.0): 1.2.0
 - PyTorch Version (e.g. 1.0): 1.12.1
 - CPU Architecture:
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): pip
 - Build command you used (if compiling from source):
 - Are you using local sources or building from archives:
 - Python version: 3.8
 - CUDA version: 11.6
 - GPU models and configuration:
 - Any other relevant information:

### PR DESCRIPTION
**Pull request by gs-olive**
# Description

Resolves a CUDA 710 error Issue arising when compiling BERT models with 3+ inputs. The issue arises due to the role of the third tensor in inference computations. Specifically, as specified in the [BERT model code linked here](https://github.com/huggingface/transformers/blob/15fd39ea0ec4f826deb4cb8f3064004939544d30/src/transformers/models/bert/modeling_bert.py#L812-L835), the third argument, `token_type_ids` is of type `torch.LongTensor`, but can only take indices in $[0,1]$. This means that when values outside of this set are used, the input is invalid.

This becomes problematic when the inputs are, for example, indices in a dictionary or embedding - which seems to be the case here. Specifically, `aten::embedding` is used with Tensors which are the product of `token_type_ids`. The issue traces to one line in the `shape_analysis` code previewed below, which initializes a random tensor with values in the range $[0,4]$.

```cpp
// shape_analysis.cpp [Line 23, Commit 5f3a5a3]
auto in = at::randint(5, shape, {at::kCUDA}).to(type);
```

This tensor is run through the `forward` function of the module to determine the shapes of outputs and causes the model compilation-time error, as featured [here](https://github.com/pytorch/TensorRT/blob/5a7f00e8db1ca1d974e4583657a1f03e810f15a9/core/partitioning/shape_analysis.cpp#L129) in the shape analysis code.

I have added a temporary fix by decreasing the range of allowed values to the random number generator for creating input tensors to 0-1, instead of 0-4, and am working on a more robust fix.

Fixes #1418 

## Type of change

Please delete options that are not relevant and/or add your own.

- Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [ x ] My code follows the style guidelines of this project (You can use the linters)
- [ x ] I have performed a self-review of my own code
- [ x ] I have commented my code, particularly in hard-to-understand areas and hacks
- [ x ] I have made corresponding changes to the documentation
- [ x ] I have added tests to verify my fix or my feature
- [ x ] New and existing unit tests pass locally with my changes
- [ x ] I have added the relevant labels to my PR in so that relevant reviewers are notified

### CODE REVIEW

File: core/partitioning/shape_analysis.cpp [hunk 1]
```diff
@@ -12,16 +12,22 @@ namespace partitioning {
...
   auto type = at::kFloat;
   if (type_opt) {
     type = type_opt.value();
   } else {
     LOG_WARNING("Input type for doing shape analysis could not be determined, defaulting to F32");
   }
-  auto in = at::randint(5, shape, {at::kCUDA}).to(type);
-  // ivalue_map[input.first] = in.clone();
+
+  auto in = at::randint(LoValIncl, HiValExcl, shape, {at::kCUDA}).to(type);
```
Comment (gs-olive) [inline core/partitioning/shape_analysis.cpp:29]: This could potentially just be `at::zeros`, as it is currently only selecting between `0` and `1`. Is there a benefit to including nonzero values in the forward run conducted during partitioning?

**Comment by narendasan** [comment]
@bowang007 Make sure to review this

**Comment by narendasan** [comment]
From my perspective see nothing wrong with sampling between $[0,1)$

File: core/partitioning/shape_analysis.cpp [hunk 2]
```diff
@@ -12,16 +12,24 @@ namespace partitioning {
...
     type = type_opt.value();
   } else {
     LOG_WARNING("Input type for doing shape analysis could not be determined, defaulting to F32");
   }
-  auto in = at::randint(5, shape, {at::kCUDA}).to(type);
-  // ivalue_map[input.first] = in.clone();
+
+  // Make the value range for input tensor a uniform (float) distribution
+  // over [LoValIncl, HiValExcl), then cast to the desired dtype
+  auto in = ((HiValExcl - LoValIncl) * at::rand(shape, {at::kCUDA}) + LoValIncl).to(type);
```
Comment (gs-olive) [inline core/partitioning/shape_analysis.cpp:31]: Used float inputs in the range $[0, 2)$, then casted to the desired type to avoid divide-by-zero errors potentially arising from only selecting integer random values (even for float tensors)

**Review by bowang007 — APPROVED** [review]
LGTM

File: core/partitioning/shape_analysis.cpp (hunk 2 above)
Comment (bowang007) [reply core/partitioning/shape_analysis.cpp:31]: seems like a little bit hard-coded for this model only, but will be resolved once the input range is open to users by this RFC https://github.com/pytorch/TensorRT/discussions/1425.
