### PR TITLE
fix: Error with `aten::div` when using truncation with Int32 tensor inputs

### LINKED ISSUE #1441: 🐛 [Bug] Bug encountered when compiling `Jasper10x5dr` network
##  Bug Description

When compiling the [Jasper10x5dr](https://catalog.ngc.nvidia.com/orgs/nvidia/teams/nemo/models/stt_en_jasper10x5dr) speech recognition model with Torch-TRT, the following error is displayed:

```python
ERROR: [Torch-TensorRT TorchScript Conversion Context] - 3: (Unnamed Layer* 22) [Unary]: operation FLOOR not allowed on type Int32
...
RuntimeError: [Error thrown at core/conversion/converters/impl/unsqueeze.cpp:25] Expected dim <= nbDims && dim >= -(nbDims + 1) to be true but got false
Dimension out of range (expected to be in range of [-1, 0], but got 1)
```

## To Reproduce

1. Run torch_tensorrt.compile with `Jasper10x5dr` model as input, using fp32 precision.
2. Choose fixed input sizes of [1, 64, 256] and [1,] and enable truncate_long_and_double with 8 GB workspace.

## Expected behavior

Model should successfully compile to Torch-TRT. Specifically, the floor operation should not throw an error on the input

## Environment

- Torch-TensorRT Version: 1.3.0a0+b5bcccf9
- PyTorch Version: 1.14.0.dev20221018+cu116
- CPU Architecture: Intel Xeon CPU
- OS: Ubuntu 20.04
- How you installed PyTorch: pip
- Build command you used: python setup.py develop
- Are you using local sources or building from archives: local
- Python version: 3.8.13
- CUDA version: 11.6

### PR DESCRIPTION
**Pull request by gs-olive**
# Description
- `aten::div` with truncation on integer tensor inputs currently throws an error if both inputs are integer type, as the TRT unary operations for absolute value and floor do not apply to Int32 or Bool types
- For absolute value, this is a legitimate bug as `aten::abs` is functional for integer types
- For the floor operation, `aten::floor` does not explicitly support integer inputs, and `torch.floor()` does not work with Int32 inputs by default (on `1.13.0.dev20220921+cu116`). However, `torch.div(..., rounding_mode="trunc")` with integer tensors does return an integer value, and so the corollary Torch-TRT converter should behave similarly
- Modified `aten:abs` converter logic to be a utility (moved file location), as the operator is used in multiple locations
- Added regression test to ensure truncation divide with two integer tensors is functional

Note: The behavior of `torch.floor()` on Int32 types differs between `1.13.0.dev20220921+cu116` and `1.14.0.dev20221018+cu116`: the former does not by default support this operation, while the latter does. This PR does not fix the general `aten::floor` operator for Int32 inputs, but instead fixes the `aten::div` truncation operator only.

Fixes #1441 
Note: The issue was traced to a problem with `aten::div` with truncation enabled, and not `aten::floor`

## Type of change

- Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [ x ] My code follows the style guidelines of this project (You can use the linters)
- [ x ] I have performed a self-review of my own code
- [ x ] I have commented my code, particularly in hard-to-understand areas and hacks
- [ x ] I have made corresponding changes to the documentation
- [ x ] I have added tests to verify my fix or my feature
- [ x ] New and existing unit tests pass locally with my changes
- [ x ] I have added the relevant labels to my PR in so that relevant reviewers are notified

### CODE REVIEW

File: core/conversion/converters/impl/element_wise.cpp [hunk 1]
```diff
@@ -326,8 +326,24 @@ auto element_wise_registrations TORCHTRT_UNUSED =
...
+                   LOG_GRAPH(
+                       "Tensor is of unsupported type " << abs->getOutput(0)->getType()
+                                                        << " for IUnaryLayer::kFLOOR. Using identity instead.");
+                   floor = ctx->net->addIdentity(*abs->getOutput(0));
+                   TORCHTRT_CHECK(floor, "Unable to create identity layer from node: " << *n);
+                 } else {
+                   floor = ctx->net->addUnary(*abs->getOutput(0), nvinfer1::UnaryOperation::kFLOOR);
+                   TORCHTRT_CHECK(floor, "Unable to create floor layer from node: " << *n);
+                 }
+                 floor->setName((util::node_info(n) + "_floor").c_str());
```
Comment (gs-olive) [inline core/conversion/converters/impl/element_wise.cpp:345]: In this code block, both the `abs` and the `floor` operators were encountering errors when both inputs are integer types. The solution for `abs` was a converter utility, whereas for `floor`, the solution only appears here. The reasoning for this choice was that Torch support for `torch.floor()` applied to an Int32 type differs between `1.13.0.dev20220921+cu116` and `1.14.0.dev20221018+cu116`, so it is unclear if the `aten::floor` converter should generally support Int32 inputs or not, currently.

File: core/conversion/converters/impl/element_wise.cpp [hunk 2]
```diff
@@ -326,8 +326,24 @@ auto element_wise_registrations TORCHTRT_UNUSED =
...
-                 auto abs = ctx->net->addUnary(*tmp_div->getOutput(0), nvinfer1::UnaryOperation::kABS);
-                 auto floor = ctx->net->addUnary(*abs->getOutput(0), nvinfer1::UnaryOperation::kFLOOR);
+                 auto abs = add_absolute_value(ctx, n, tmp_div->getOutput(0), util::node_info(n) + "_absolute_val");
+
+                 // In this case, we allow the floor unary on non-TRT Unary types, as it is needed for this
+                 // specific function. Floor applied to non-float types equates to identity
+                 nvinfer1::ILayer* floor;
+                 if ((abs->getOutput(0)->getType() == nvinfer1::DataType::kINT32) ||
+                     (abs->getOutput(0)->getType() == nvinfer1::DataType::kBOOL)) {
+                   LOG_GRAPH(
```
Comment (narendasan) [inline core/conversion/converters/impl/element_wise.cpp:336]: LOG_DEBUG instead of LOG_GRAPH

File: core/conversion/converters/impl/element_wise.cpp [hunk 3]
```diff
@@ -326,8 +326,24 @@ auto element_wise_registrations TORCHTRT_UNUSED =
                } else if (rounding_mode == "trunc") {
                  // trunc = floor(abs(div)) * sign(div)
                  auto tmp_div = add_elementwise(ctx, nvinfer1::ElementWiseOperation::kDIV, self, other, "tmp_div");
-                 auto abs = ctx->net->addUnary(*tmp_div->getOutput(0), nvinfer1::UnaryOperation::kABS);
-                 auto floor = ctx->net->addUnary(*abs->getOutput(0), nvinfer1::UnaryOperation::kFLOOR);
+                 auto abs = add_absolute_value(ctx, n, tmp_div->getOutput(0), util::node_info(n) + "_absolute_val");
+
+                 // In this case, we allow the floor unary on non-TRT Unary types, as it is needed for this
+                 // specific function. Floor applied to non-float types equates to identity
+                 nvinfer1::ILayer* floor;
```
Comment (narendasan) [inline core/conversion/converters/impl/element_wise.cpp:333]: Work with ITensor* instead ideally

File: core/conversion/converters/impl/element_wise.cpp (hunk 1 above)
Comment (narendasan) [inline core/conversion/converters/impl/element_wise.cpp:345]: This needs to only be applied to the unary layer on line 342 so as not to overwrite the info from the abs on 329

File: core/conversion/converters/converter_util.cpp [hunk 4]
```diff
@@ -156,6 +156,38 @@ nvinfer1::ILayer* add_elementwise(
...
+    auto neg_one_const = tensor_to_const(ctx, neg_one);
+    auto neg_layer = add_elementwise(
+        ctx, nvinfer1::ElementWiseOperation::kPROD, self, neg_one_const, util::node_info(n) + std::string("_Negation"));
+    TORCHTRT_CHECK(neg_layer, "Unable to create prod layer from node: " << *n);
+    absolute_value_layer =
+        add_elementwise(ctx, nvinfer1::ElementWiseOperation::kMAX, self, neg_layer->getOutput(0), name);
+    TORCHTRT_CHECK(absolute_value_layer, "Unable to create max layer from node: " << *n);
+  }
+
+  return absolute_value_layer->getOutput(0);
```
Comment (gs-olive) [inline core/conversion/converters/converter_util.cpp:188]: Switched function schema to return the output of the absolute value layer and not the layer itself

File: core/conversion/converters/impl/element_wise.cpp [hunk 5]
```diff
@@ -326,15 +326,27 @@ auto element_wise_registrations TORCHTRT_UNUSED =
...
+
+                 // In this case, we allow the floor unary on non-TRT Unary types, as it is needed for this
+                 // specific function. Floor applied to non-float types equates to identity
+                 nvinfer1::ITensor* floor;
+
+                 if ((abs->getType() == nvinfer1::DataType::kINT32) || (abs->getType() == nvinfer1::DataType::kBOOL)) {
+                   LOG_DEBUG(
+                       "Tensor is of unsupported type " << abs->getType()
+                                                        << " for IUnaryLayer::kFLOOR. Using identity instead.");
+                   floor = abs;
```
Comment (gs-olive) [inline core/conversion/converters/impl/element_wise.cpp:339]: Instead of using the identity function, the floor output tensor is just set to the absolute value result, to avoid unnecessary computation.

**Review by narendasan — APPROVED** [review]
LGTM
