### PR TITLE
fix: Replace `RemoveDropout` lowering pass implementation with modified JIT pass

### LINKED ISSUE #1587: 🐛 [Bug] Error when compiling Punctuation BERT model
##  Bug Description

When compiling the [BERT punctuation/capitalization](https://catalog.ngc.nvidia.com/orgs/nvidia/teams/tao/models/punctuationcapitalization_english_bert) model, the following error is encountered:

```python
RuntimeError: outputs_[i]->uses().empty() INTERNAL ASSERT FAILED at "../torch/csrc/jit/ir/ir.cpp":1312, please report a bug to PyTorch. 
```

## To Reproduce

1. Run torch_tensorrt.compile with the BERT punctuation model as input, using fp32 precision.
2. Choose three fixed-size inputs of shape [1, 256], [1, 256], and [1, 256], and enable truncate_long_and_double with 12 GB workspace.

## Expected behavior

Model should successfully compile with Torch-TRT. Specifically, internal assertion errors of this sort should not occur.

## Environment

- Torch-TensorRT Version: 1.4.0.dev0+f43be5b6
- PyTorch Version: 1.14.0.dev20221114+cu116
- CPU Architecture: Intel Xeon CPU
- OS: Ubuntu 20.04
- How you installed PyTorch: pip
- Build command you used: `python setup.py develop`
- Are you using local sources or building from archives: local
- Python version: 3.8.13
- CUDA version: 11.6

## Additional context + Temporary Solution

Upon inspecting the error in greater depth, it seems to occur in the Lowering phase, during the `RemoveDropout` lowering pass:
https://github.com/pytorch/TensorRT/blob/5fa63743fc4448e38b1e6b01e7403c0d74717158/core/lowering/passes/remove_dropout.cpp#L10
The model was in evaluation mode, but it seems that one of the rewrites/replacements used in this lowering pass causes the above error. Disabling this lowering pass and recompiling the model causes the compilation to proceed normally.

### PR DESCRIPTION
**Pull request by gs-olive**
# Description
- Remove existing dropout removal lowering pass implementation due to bug
- Use adapted Torch JIT dropout removal lowering pass to resolve bug where nested dropouts resulted in invalid graph
- Existing removal process left artifacts in graph which caused an internal assertion error
- Add two regression tests to catch nested dropout bug

Fixes #1587 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [ x ] My code follows the style guidelines of this project (You can use the linters)
- [ x ] I have performed a self-review of my own code
- [ x ] I have commented my code, particularly in hard-to-understand areas and hacks
- [ x ] I have made corresponding changes to the documentation
- [ x ] I have added tests to verify my fix or my feature
- [ x ] New and existing unit tests pass locally with my changes
- [ x ] I have added the relevant labels to my PR in so that relevant reviewers are notified

### CODE REVIEW

File: tests/core/lowering/test_remove_dropout_pass.cpp [hunk 1]
```diff
@@ -32,39 +32,15 @@ TEST(LoweringPasses, RemoveDropoutLowersCorrectly) {
...
     graph(%x.1):
       %3 : float = prim::Constant[value=0.5]()
       %4 : bool = prim::Constant[value=0]()
-      %y.1 : Tensor = aten::feature_dropout(%x.1, %3, %4)
-      %11 : Tensor = aten::relu(%y.1)
-      return (%11))IR";
+      %y.1 : Tensor = aten::dropout(%x.1, %3, %4)
+      %z.1 : Tensor = aten::dropout(%y.1, %3, %4)
+      %12 : Tensor = aten::relu(%z.1)
+      return (%12))IR";
```
Comment (gs-olive) [inline tests/core/lowering/test_remove_dropout_pass.cpp:43]: This test case elicits the bug - using the original `RemoveDropout`, the lowering pass encounters a JIT assertion error due to dangling outputs.

File: core/lowering/passes/remove_dropout.cpp [hunk 2]
```diff
@@ -8,85 +9,7 @@ namespace lowering {
...
-  remove_feature_alpha_dropout_pattern.runOnGraph(graph);
-
-  // remove feature_alpha_dropout inplace
-  std::string feature_alpha_dropout_inplace_pattern = R"IR(
-        graph(%input, %4, %5):
-            %6 = aten::feature_alpha_dropout_(%input, %4, %5)
-            return (%6))IR";
-  std::string no_feature_alpha_dropout_inplace_pattern = R"IR(
-        graph(%input, %4, %5):
-            return (%input))IR";
```
Comment (gs-olive) [inline core/lowering/passes/remove_dropout.cpp:83]: The new lowering pass **does not** remove these two operators, currently. See the discussion in the main description of the PR for additional details.

File: tests/core/lowering/test_remove_dropout_pass.cpp (hunk 1 above)
Comment (narendasan) [reply tests/core/lowering/test_remove_dropout_pass.cpp:43]: Do some of the clean up passes help with this? Like RemoveDeadCode

Comment (gs-olive) [reply tests/core/lowering/test_remove_dropout_pass.cpp:43]: No, other passes don't seem to help in this case because the error originates from within the `RemoveDropout` lowering pass itself. It seems that the graph is put into an inconsistent state during lowering, so when the rewrite pattern is run on the graph, it crashes entirely. Running `EliminateDeadCode` before the `RemoveDropout` lowering pass will not help, as the `aten::dropout` code is considered to be in-use, and running it after also does not work since the crash occurs within `RemoveDropout`.

File: core/lowering/passes/remove_dropout.cpp [hunk 3]
```diff
@@ -1,92 +1,55 @@
...
+
+  // Delete dropout nodes
+  for (auto del_node : dropout_nodes_to_remove) {
+    del_node->destroy();
+  }
+}
 
+void RemoveDropout(std::shared_ptr<torch::jit::Graph>& graph) {
+  // Remove all instances of dropout variants from graph
+  removeDropoutInBlock(graph->block());
```
Comment (narendasan) [inline core/lowering/passes/remove_dropout.cpp:52]: Would we want to run dead code elimination here just to make sure the graph is clean for the next pass?

Comment (gs-olive) [reply core/lowering/passes/remove_dropout.cpp:53]: Thanks for the suggestion - that sounds good, I have now added the dead code elimination

**Review by narendasan — APPROVED** [review]
LGTM
